[package]
name = "l11"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
slog = "2.7.0"
slog-term = "2.9.1"
